---
title: Water
subtitle: Long-Term Trends in Groundwater Levels in B.C. Methods
bibliography: gwl.bib
output:
  pdf_document:
    template: D:/templates/print_ver_template.tex
---

Observation well groundwater level time-series data were downloaded from
the B.C. Ministry of Environment Groundwater Observation Well Network
web application:
<http://www.env.gov.bc.ca/wsd/data_searches/obswell/map/obsWells.html>.
Well metadata, such as location, depth, and aquifer type were obtained
from the Ground Water Wells (Spatial View) dataset available from
DataBC:
<http://www.data.gov.bc.ca/dbc/catalogue/detail.page?config=dbc&P110=recorduid:173681>.
All data preparation and analysis was performed using the statistical
software R [@baseR].

Trend analysis was conducted using monthly groundwater levels from each
groundwater observation well that had more than ten years of data, fewer
than 25% of monthly observations missing, and was active as of Jauary 1,
2004. This resulted in 118 wells with suitable records for analysis. For
each month that had more than one observation, the median was taken.
Missing values were interpolated by first fitting a 12-period (i.e.,
monthly) basic structural time series model (BSM) to the data
[@harvey1990forecasting]. Fixed- interval smoothing
[@DurbinKoopman2001ts] was then applied to the fitted model to generate
predicted values for the entire time series; the predicted values were
substituted into the orignal time series where there were missing data.
This resulted in a full monthly time series for each well, with one
observation per month. After the time series were constructed, each was
inspected for consecutive missing (interpolated) values near the
beginning or the end of the time series, due to the strong influence of
these regions on trend analysis. If there were more than four
consecutive missing values in the first or last 10% of the time series,
the time series was truncated to remove the missing values. Finally, the
mean annual groundwater level was calculated for each well, and trend
analysis was performed using the annual values.

Each groundwater-level time series was analyzed for trend using
Trend-Free Pre- Whitening to remove lag-1 autocorrelation, which can
artificially increase the probability of detecting a significant trend
[@YuePilon2002autocorr]. In this method, the slope of each time series
is estimated using the Theil-Sen approach [@sen1968slope]. If the
estimated slope is different from zero, then the data are detrended by
the slope and the AR(1) 1s calculated for the detrended time series. The
residuals and the trend are combined and then tested for significance
using the Mann-Kendall trend test. These methods were implemented using
the R package ‘zyp’ [@pkg_zyp].

Time series were not corrected for precipitation or any other climatic
or hydrologic process. As such no causation for trends are implied.

Wells were classified as exhibiting a ‘large rate of decline’, ‘moderate
rate of decline’, ‘stable’, or ‘increasing’ trends, based on the
magnitude and significance of the calculated trend. If the slope was
significantly different from zero ($P$ \<0.05) and declined at more than
ten cm per year, the well was considered to have a large rate of
decline. If the slope was significant and declining at a rate between
three and ten cm peryear, it was classified as having a moderate rate of
decline. If the slope was significant and increasing at greater than 3
cm per year, it was classified as increasing. All other wells were
classified as stable.

\*Email correspondence to:
[envreportbc@gov.bc.ca](mailto:EnvReportBC@gov.bc.ca)

## References

