---
topic: "water"
title: "Long-Term Trends in Groundwater Levels in B.C."
output: envreportutils.internal::print_ver

---
<!--
Copyright 2018 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->



```{r setup, echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE}

library(dplyr)
library(ggplot2)
library(grid)
library(RColorBrewer)
library(scales)
library(bcgroundwater)
library(envreportutils)
library(gridExtra)
library(xtable)
library(lubridate)
library(forcats)

knitr::opts_chunk$set(cache = FALSE)

base_theme <- theme_get()


load('../tmp/results_viz.RData')
load('../tmp/well_plots.RData')


attr_wells <- results_viz

state.summary <- table(attr_wells$state)
state.summary <- cbind(n = state.summary, prop = prop.table(state.summary))

theme_set(theme_classic() +
            theme(text = element_text(colour = "black"),
                  axis.line = element_blank(),
                  axis.ticks = element_blank(),
                  panel.grid.major = element_line(colour = "grey85", size = 0.5,
                                                linetype = 1),
                  panel.grid.minor = element_line(colour = "grey90", size = 0.5,
                                                linetype = 1),
                  panel.grid.major.x = element_blank(),
                  panel.spacing = unit(0.6, "lines"),
                  plot.title = element_text(vjust = 2, hjust = 0.5),
                  axis.title = element_text(vjust = 0.1),
                  legend.position = "bottom", legend.title = element_blank(),
                  legend.text = element_text(size = 12),
                  axis.text.x = element_blank(),
                  strip.background = element_blank()))

label.colour <- "black" 
colour.scale <- brewer.pal(3,"Blues")

updateDate <- format(Sys.Date(), "%B %Y")
```

## Appendix


```{r well_plots, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, results = 'asis', fig.height = 7.5, dev = "pdf"}

knitr_latex_char <- function(x) {
  y <- gsub("\\\\", "\\\\textbackslash{}", x) # backslash has to be first!
  y <- gsub("([#$%&_])", "\\\\\\1", y) # Doesn't deal with { or } because of function{}
  y <- gsub("\\^", "\\\\textasciicircum{}", y)
  y <- gsub("~", "\\\\textasciitilde{}", y)
  return(y)
}

theme_set(base_theme)

for (reg in sort(unique(attr_wells$REGION_NAME))) {
  cat(paste0('\\subsection{',reg," Region",'}'))
  regdata <- filter(attr_wells, REGION_NAME == reg)
  
  for (well in regdata$Well_Num) {
    if (is.na(well)) next
    
    wellname <- filter(regdata, Well_Num == well) %>%
      pull(Well_Name)
    
    cat(paste0('\\subsubsection*{',reg,": ",
               knitr_latex_char(wellname),
               '}'))
    
    # cat(paste0("This provincial groundwater observation well is drilled into a ",
    #            well.attr$AQUIFER_TYPE, 
    #            " aquifer to a depth of ", well.attr$wellDepth_m, 
    #            " metres. The well has a monitoring period of record from ", 
    #            format(well.attr$start_date, format = "%B %d %Y"), 
    #            " to ", format(well.attr$last_date, format = "%B %d %Y"), ". \\newline",
    #            "\\newline"))
    
    mapplot <- filter(well_plots, Well_Num == well) %>% pull(map_plot)
    monthplot <- filter(well_plots, Well_Num == well) %>% pull(month_plot)
    areaplot <- filter(well_plots, Well_Num == well) %>% pull(area_plot)
    
    grid.arrange(mapplot[[1]] + theme(text = element_text(size = 10),
                                 plot.margin = unit(c(0,0.5,0,0.01),"cm")),
                 monthplot[[1]] + theme(axis.text = element_text(size = 8),
                                   axis.title.x = element_text(face = "bold", size = 8),
                                   plot.title = element_text(size = 10, face = "bold"),
                                   axis.title.y = element_text(size = 8,
                                                               hjust = 0.5,
                                                               vjust = -.8,
                                                               face = "bold"),
                                   legend.box = "vertical",
                                   legend.position = "top",
                                   legend.text = element_text(size = 9),
                                   plot.margin = unit(c(1,0.01,1,0.01),"cm"),
                                   legend.spacing.y = unit(-.4, 'cm')),
                 areaplot[[1]] + theme(axis.text = element_text(size = 8),
                                  axis.title.x = element_text(face = "bold", size = 8),
                                  axis.title.y = element_text(size = 8,
                                                              hjust = 0.5,
                                                              vjust = -.8,
                                                              face = "bold"),
                                  legend.text = element_text(size = 9),
                                  plot.title = element_text(size = 11, face = "bold"),
                                  plot.subtitle = element_text(size = 9),
                                  plot.margin = unit(c(0.5,0.5,0.5,0.01),"cm")),
                 layout_matrix = matrix(c(1,2,3,3), nrow = 2, byrow = TRUE))
    
    cat('\\newpage ')
  }
  
}
```

\newpage